declare interface BlockData {
  blockNumber?: BigInt;
  blockTimestamp?: BigInt;
  transactionHash?: string;
}

declare interface Hypercert extends BlockData {
  id: string; // Generated by The Graph
  tokenID: number;
  owner: `Ox${string}`; // what we check against for showing users hypercerts
  creator: `Ox${string}`;
  uri?: string;
  creation: number
}

declare interface HypercertUI extends Hypercert {
  name: string;
  description?: string;
  logo?: string;
  banner?: string;
  workScope: string[];
  allowList: string[];
  startedAt: string;
  endedAt?: string;
  contributors?: `0x${string}`[]; 
}

